theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "aqua"
name: "János Kondri"
title: "Data Portfolio - János Kondri"
logo: "assets/profile_pic_MAIN.png"
description: "Bookmark this to keep an eye on my project updates!"
show_downloads: false

