theme: jekyll-theme-minimal
title: JÃ¡nos Kondri`s Data Projects Portfolio
logo: https://github.com/jameszka997/Data-Portfolio/blob/main/assets/profile_pic_MAIN.png
description: Bookmark this to keep an eye on my project updates!
show_downloads: true
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
